project_name: "malaria_detection_dinov2"
data:
  batch_size: 32
  image_size: 224
  val_split: 0.2
training:
  epochs: 3
  learning_rate: 0.0001
  device: "cuda"
model:
  name: "facebook/dinov2-small"
  num_classes: 1
